### ISSUE TITLE
Double keys

### ISSUE THREAD

**Issue by vishalc07** [roboremo/ESP8266-WiFi-UART-Bridge#5]
Hey,

I'm using putty in windows, but when I press enter, it happen twice
![image](https://user-images.githubusercontent.com/64244691/155653431-234e2867-b37d-4cf1-a111-414165b6477e.png)

**Comment by geomatik** [comment]
Not an expert here but the problem is probably about newline characters related. Try using [netcat](https://en.wikipedia.org/wiki/Netcat). On windows you can find Netcat in [Cygwin](https://cygwin.com/packages/summary/nc.html) or [MSYS2](https://packages.msys2.org/package/netcat?repo=msys&variant=x86_64)

**Comment by vishalc07** [comment]
Thanks for update, but it is resolved now
